services:
  - type: web
    name: laravel-app
    runtime: docker
    repo: https://github.com/your-username/your-laravel-repo
    branch: main
    plan: free
    env: docker
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
    startCommand: |
      php artisan migrate --force
      php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:HRLAtXQFBsPOCEm5fSezHDYChcq9P9y3tklRB8CeI94=
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/data/database.sqlite

    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
